valbok/QtAVPlayer

- src/QtAVPlayer/qavplayer.cpp
Not sure if this is right solution from the current design prospective, but the idea is to delay switching to 'wait mode' till first video frame will be reached. This way seeking while paused is possible.
#3
> seek to the first video frame

- src/QtAVPlayer/qavcodec.cpp
- src/QtAVPlayer/qavcodec_p.h
- src/QtAVPlayer/qavcodec_p_p.h
should solve https://github.com/valbok/QtAVPlayer/issues/18
> fix build issue with the latest ffmpeg

- examples/qml_video/main.cpp
- src/QtAVPlayer/qavaudioframe.cpp
- src/QtAVPlayer/qavaudioframe.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
- src/QtAVPlayer/qavvideoframe.cpp
- src/QtAVPlayer/qavvideoframe.h
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
> Remove dispatchin frames on main thread

- src/QtAVPlayer/qavplayer.cpp
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
No need to proceed new events if current one has failed
> Fix events handling

- src/QtAVPlayer/qavvideocodec.cpp
Don't use hw format if it is not supported
> Respect choices from ffmpeg

- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
All frames will be sent immediately
> Introduce isSynced

- src/QtAVPlayer/qavvideoframe.cpp
Also metal impl requires NV12 format somehow.
> Use planes from textures if any

- src/QtAVPlayer/qavvideoframe.cpp
> Qt6: Fix software rendering

- .github/workflows/main.yaml
- src/QtAVPlayer/QtAVPlayer.pro
- src/QtAVPlayer/qavaudiofilter.cpp
- src/QtAVPlayer/qavaudiofilter_p.h
- src/QtAVPlayer/qavaudioinputfilter.cpp
- src/QtAVPlayer/qavaudiooutputfilter.cpp
- src/QtAVPlayer/qavfilter.cpp
- src/QtAVPlayer/qavfilter_p.h
- src/QtAVPlayer/qavfilter_p_p.h
- src/QtAVPlayer/qavfiltergraph.cpp
- src/QtAVPlayer/qavframe.cpp
- src/QtAVPlayer/qavframe.h
- src/QtAVPlayer/qavframe_p.h
- src/QtAVPlayer/qavinoutfilter.cpp
- src/QtAVPlayer/qavinoutfilter_p.h
- src/QtAVPlayer/qavinoutfilter_p_p.h
- src/QtAVPlayer/qavpacketqueue_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
- src/QtAVPlayer/qavvideofilter.cpp
- src/QtAVPlayer/qavvideofilter_p.h
- src/QtAVPlayer/qavvideoinputfilter.cpp
- src/QtAVPlayer/qavvideooutputfilter.cpp
- tests/auto/integration/qavdemuxer/qavdemuxer.pro
- tests/auto/integration/qavplayer/qavplayer.pro
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
Returns AVFilterInOut->name where the frame was retrieved from.
> Introduce QAVFrame::filterInOutName

- .github/workflows/main.yaml
- src/QtAVPlayer/CMakeLists.txt
- src/QtAVPlayer/QtAVPlayer.pro
- src/QtAVPlayer/qavaudiofilter.cpp
- src/QtAVPlayer/qavfilters.cpp
- src/QtAVPlayer/qavfilters_p.h
- src/QtAVPlayer/qavpacketqueue_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavvideofilter.cpp
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
Now if there are multiple filters applied
one step (using pause/stepForward/stepBackward) should return number of frames equal number of filter outputs.
> Introduce stepping with multiple filters

- src/QtAVPlayer/qavdemuxer.cpp
- src/QtAVPlayer/qavdemuxer_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
- tests/auto/integration/qavdemuxer/tst_qavdemuxer.cpp
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
> Introduce inputFormat

- src/QtAVPlayer/qavaudiofilter.cpp
- src/QtAVPlayer/qavaudiofilter_p.h
- src/QtAVPlayer/qavfilter_p.h
- src/QtAVPlayer/qavfilters.cpp
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavvideofilter.cpp
- src/QtAVPlayer/qavvideofilter_p.h
Since it never returns anything
> Change return type from int to void for QAVFilter::read

- src/QtAVPlayer/qavpacketqueue_p.h
- src/QtAVPlayer/qavplayer.cpp
> Return last sent pts of the frame

- src/QtAVPlayer/qavaudioformat.h
- src/QtAVPlayer/qavaudioframe.cpp
- src/QtAVPlayer/qavaudioframe.h
- src/QtAVPlayer/qavaudiooutput.cpp
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
```cpp
fmt = audioFrame.format();
audioOutput.play({fmt, data});
```
> Introduce custom QAVAudioFrame

- .github/workflows/main.yaml
> Revert "Fix macOS CI"

- src/QtAVPlayer/qavplayer.cpp
A simple fix to use Q_EMIT instead emit as keyword.
> Do not use QT_NO_KEYWORDS to compile.

- src/QtAVPlayer/qavdemuxer.cpp
> Fix memory leak due to not clearing AVDictionary

- src/QtAVPlayer/qavplayer.cpp
It allows to terminate not started stream
> Abort before waiting

- src/QtAVPlayer/qavcodec.cpp
- src/QtAVPlayer/qavcodec_p.h
- src/QtAVPlayer/qavdemuxer.cpp
- src/QtAVPlayer/qavdemuxer_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
https://github.com/valbok/QtAVPlayer/issues/504
> Provide QAVPlayer::setCodecOptions API

- src/QtAVPlayer/qavdemuxer.cpp
- src/QtAVPlayer/qavdemuxer_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
To access container FFmpeg data
Fixes #507
> 'Provide QAVPlayer::avctx API

- examples/qml_video/main.cpp
- src/QtAVPlayer/QtAVPlayer.cmake
- src/QtAVPlayer/QtAVPlayer.pri
- src/QtAVPlayer/qavaudiocodec.cpp
- src/QtAVPlayer/qavaudiocodec_p.h
- src/QtAVPlayer/qavcodec.cpp
- src/QtAVPlayer/qavcodec_p.h
- src/QtAVPlayer/qavdemuxer.cpp
- src/QtAVPlayer/qavdemuxer_p.h
- src/QtAVPlayer/qavframecodec.cpp
- src/QtAVPlayer/qavframecodec_p.h
- src/QtAVPlayer/qavmuxer.cpp
- src/QtAVPlayer/qavmuxer_p.h
- src/QtAVPlayer/qavpacket.cpp
- src/QtAVPlayer/qavpacket_p.h
- src/QtAVPlayer/qavplayer.cpp
- src/QtAVPlayer/qavplayer.h
- src/QtAVPlayer/qavstreamframe.cpp
- src/QtAVPlayer/qavstreamframe.h
- src/QtAVPlayer/qavsubtitlecodec.cpp
- src/QtAVPlayer/qavsubtitlecodec_p.h
- src/QtAVPlayer/qavvideocodec.cpp
- src/QtAVPlayer/qavvideocodec_p.h
- tests/auto/integration/qavdemuxer/tst_qavdemuxer.cpp
- tests/auto/integration/qavplayer/tst_qavplayer.cpp
Added `QAVMuxer` to mux and write streams to output file.
> Introduce QAVMuxer
